name: Generate Repo Info

on:
  push

permissions:
  contents: write

jobs:
  generate-repo-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Fetch all branches
        run: |
          git fetch origin
          for branch in $(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||'); do
            if [ "$branch" != "main" ]; then
              git fetch origin $branch:$branch
            fi
          done

      - name: Generate repo_info.txt with commit details
        run: |
          echo "Branches in this repo (with details):" > repo_info.txt
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            echo "" >> repo_info.txt
            echo "- $branch" >> repo_info.txt

            sha=$(git rev-parse "$branch")
            echo "  SHA: $sha" >> repo_info.txt

            count=$(git rev-list "$branch" --count)
            echo "  Commits: $count" >> repo_info.txt

            echo "  Recent commits:" >> repo_info.txt
            git log "$branch" \
              --pretty=format:'    %h | Author: %an <%ae> | Committer: %cn <%ce> | Date: %ad | %s' \
              --date=iso-strict -n 5 >> repo_info.txt
          done

          echo "✅ repo_info.txt generated:"
          cat repo_info.txt

      - name: Commit and push repo_info.txt to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add repo_info.txt
          git commit -m "Auto-update repo_info.txt" || echo "No changes to commit"
          git push origin main
